### Comparison of Pharmacy First consultation counts in GP records and NHS BSA data

To contextualise the Pharmacy First consultation data in OpenSAFELY-TPP, we compared it with publicly available NHS Business Services Authority (NHS BSA) data.
NHS BSA captures 100% of reimbursed Pharmacy First consultations in England, based on monthly service activity submitted by community pharmacies.
We used the *Pharmacy and Appliance Contractor Dispensing Dataset*, which reports monthly counts for Pharmacy First Clinical Pathways, and report overall consultation totals as well as the proportion of NHS BSA-recorded consultations captured in OpenSAFELY-TPP over time.

**Figure X**. Monthly counts and ratio of patients with a Pharmacy First consultation code in OpenSAFELY-TPP and the NHS BSA comparison dataset.

```{r, message=FALSE, warning=FALSE, fig.height=4, fig.width=10}
# Ideally I would like to load this at the top of this script
# But this file uses datasets created further down so it easiest to load it here
df_pf_consultations_total <- df_pf_consultations |>
  filter(data_desc == "Total") |>
  mutate(
    data_desc = "Pharmacy First Consultation"
  ) |>
  select(interval_start, pf_consultation_total = value, data_desc) |>
  unique()

source(here("lib", "functions", "combine_os_nhsbsa_validation_data.R"))

# Creates comparison dataset by combining datasets listed in arguments
df_pf_consultation_validation_plot <- generate_validation_comparison_dataset(
  df_bsa_validation,
  df_measures,
  df_pf_consultations_total,
  df_pfmed
)

# Select colours for groups
# Group 1:
colour_group_1 <- "#CF4446FF"
# Group 1: #1B0C42FFpaletteer_c("viridis::inferno", n = 10)[2]
colour_group_2 <- "#1B0C42FF"

# Create consultation validation plot
pf_validatio_consultation_plot <- df_pf_consultation_validation_plot |>
  ggplot(aes(x = date)) +
  geom_point(
    aes(
      y = nhs_bsa_count_100pct,
      colour = "NHS BSA",
      shape = "NHS BSA"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(y = nhs_bsa_count_100pct, colour = "NHS BSA"),
    alpha = .3,
    linewidth = .5
  ) +
  geom_point(
    aes(
      y = opensafely_opensafely_tpp,
      colour = "OpenSAFELY-TPP",
      shape = "OpenSAFELY-TPP"
    ),
    size = 2.6
  ) +
  geom_line(
    aes(
      y = opensafely_opensafely_tpp,
      colour = "OpenSAFELY-TPP"
    ),
    alpha = .3,
    linewidth = .5
  ) +
  geom_label(
    aes(
      y = opensafely_opensafely_tpp,
      label = scales::percent(ratio, accuracy = .1),
    ),
    colour = colour_group_2,
    vjust = -.5,
    size = 3.5
  ) +
  scale_y_continuous(labels = scales::number) +
  scale_x_date(
    date_breaks = "1 month",
    labels = scales::label_date_short()
  ) +
  scale_colour_manual(
    values = c(
      "NHS BSA" = colour_group_1,
      "OpenSAFELY-TPP" = colour_group_2
    ),
    name = NULL
  ) +
  scale_shape_manual(
    values = c(
      "NHS BSA" = 15,
      "OpenSAFELY-TPP" = 16
    ),
    name = NULL
  ) +
  labs(
    x = NULL,
    y = NULL,
    colour = NULL,
    shape = NULL
  ) +
  theme(
    legend.position = "bottom",
    text = element_text(size = 14)
  )

pf_validatio_consultation_plot
```